### ISSUE TITLE
Build in powerful search parameters

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#194]
#### Description
We should build in a search parameter. This should be able to search across all the available columns.

#### Use Case
We're building a new Brigade Projects page. We need to search for projects based on arbitrary words. 

#### Examples
`/api/projects?search="ruby"` should return all projects that have the word "ruby" in any of their columns.
`/api/projects?search="health san francisco"` should return all projects that have all the words "health, san, francisco" in any order, in any of their columns.

Additionally:
`/api/organizations?search="Code for"` should return all of the "Code for" groups.
`/api/stories?search="Code Across"` should return all of the Code Across blog posts.
`/api/events?seach="Hack Night"` should return all of the Hack Nights by any Brigade.
Maybe `/api?search="Boston"` could return any Org, Story, Event, or Project with Boston in any of its columns?

**Comment by volkanunsal** [comment]
To make the search function fully-featured, I would also propose making `search` an endpoint rather than just a query parameter. 

Some thoughts on interesting queries. It would be great to ensure that the search field can be applied to a single column, such as category:

    /api/projects/search?q=ruby+column:category

When the column option is blank, it would be run on all fields by default:

    /api/projects/search?q=ruby

You should also be able to search on multiple columns:

    /api/projects/search?q=map&q=poverty+column:category
    /api/projects/search?q=map&q=education+column:category

(The first query is run on all columns, and the second one is run only on the category column.)

And you should be able to sort the results by interesting criteria:

    /api/projects/search?q=ruby&sort=relevance
    /api/projects/search?q=ruby&sort=last_updated
    /api/projects/search?q=ruby&sort=most_starred

And rank the results in ascending or descending order.

    /api/projects/search?q=ruby&sort=most_starred&order=desc

**Comment by volkanunsal** [comment]
Any thoughts about writing parts of the API in different languages?

There might also be performance benefits from deploying features that will see potentially heavy use –– search being a great example –– on more scalable platforms, such as Node or Java.

What are your thoughts about deploying search as a microservice that taps into the same database, but uses Node.js?

**Comment by migurski** [comment]
We aren’t able to support either Node.js or Java, so both are non-starters. I’ll also point out that neither is inherently more scalable. Java’s advantages only show up at scales vastly larger than our own, while the fitness of Node.js for any purpose is up for debate.
